# Generated by Django 3.0.13 on 2021-06-09 23:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Object UUID')),
                ('mood', models.IntegerField(choices=[(0, 'Happy'), (1, 'Sad'), (2, 'Fear'), (3, 'Anger')])),
                ('weather', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
